### ISSUE TITLE
go mod tidy

### ISSUE THREAD

**Issue by zhoushiya** [ngocphuongnb/tetua#5]
[root@bogon go]# git clone https://github.com/ngocphuongnb/tetua.git
Cloning into 'tetua'...
remote: Enumerating objects: 604, done.
remote: Counting objects: 100% (604/604), done.
remote: Compressing objects: 100% (368/368), done.
remote: Total 604 (delta 217), reused 587 (delta 203), pack-reused 0
Receiving objects: 100% (604/604), 561.87 KiB | 17.00 KiB/s, done.
Resolving deltas: 100% (217/217), done.
[root@bogon go]# cd tetua
[root@bogon tetua]# go mod tidy
go: finding module for package github.com/ngocphuongnb/tetua/views
github.com/ngocphuongnb/tetua/app/web imports
        github.com/ngocphuongnb/tetua/views: no matching versions for query "latest"
[root@bogon tetua]#

**Comment by ngocphuongnb** [comment]
@zhoushiya
The reason that I added the `views` directory to the `,gitignore` is that it should be generate whenever a jade file changed. But the first time run, it cause the `tidy` error because of the missing `views` package.
I just push the content of the views package, please pull the latest code and try again.

**Comment by zhoushiya** [comment]
> @zhoushiya The reason that I added the `views` directory to the `,gitignore` is that it should be generate whenever a jade file changed. But the first time run, it cause the `tidy` error because of the missing `views` package. I just push the content of the views package, please pull the latest code and try again.

thanks for reply,i can use release ,but can't build , btw ,very good program
